spring:
  servlet:
    multipart:
      max-file-size: 24MB
      max-request-size: 24MB
feign:
  httpclient:
    connection-timeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000